# Generated by Django 5.2.4 on 2025-07-22 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adms',
            fields=[
                ('id_adm', models.AutoField(primary_key=True, serialize=False)),
                ('nome_adm', models.CharField(max_length=45)),
                ('email_adm', models.CharField(max_length=45)),
                ('senha_adm', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'adms',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=70)),
                ('genero_cliente', models.CharField(max_length=15)),
                ('cpf_cliente', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone_cliente', models.CharField(max_length=45)),
                ('email_cliente', models.CharField(max_length=45)),
                ('senha_cliente', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Fotografos',
            fields=[
                ('id_fotografo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fotografo', models.CharField(max_length=70)),
                ('telefone_fotografo', models.CharField(max_length=45)),
                ('raio_atendimento_fotografo', models.CharField(max_length=70)),
                ('email_fotografo', models.CharField(max_length=45)),
                ('senha_fotografo', models.CharField(max_length=255)),
                ('descricao_fotografo', models.CharField(blank=True, max_length=200, null=True)),
                ('redesocial_fotografo', models.CharField(blank=True, max_length=45, null=True)),
                ('imagem_perfil_fotografo', models.ImageField(blank=True, null=True, upload_to='images/perfis/')),
            ],
            options={
                'db_table': 'fotografos',
            },
        ),
        migrations.CreateModel(
            name='FotografosPf',
            fields=[
                ('id_fotografo_pf', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_fotografo_pf', models.CharField(max_length=14)),
                ('apelido_profissional_fotografo_pf', models.CharField(max_length=45)),
                ('data_nascimento_fotografo_pf', models.DateField()),
                ('genero_fotografo_pf', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'fotografos_pf',
            },
        ),
        migrations.CreateModel(
            name='FotografosPj',
            fields=[
                ('id_fotografo_pj', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj_fotografo_pj', models.CharField(max_length=45)),
                ('razao_social_fotografo_pj', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fotografos_pj',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('data_contratacao_servico', models.DateField()),
                ('hora_contratacao_servico', models.TimeField()),
                ('quantidade_servico', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'servicos',
            },
        ),
        migrations.CreateModel(
            name='TiposDeServicos',
            fields=[
                ('id_tipo_de_servico', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_tipo_de_servico', models.CharField(max_length=100)),
                ('valor_tipo_de_servico', models.FloatField()),
            ],
            options={
                'db_table': 'tipos_de_servicos',
            },
        ),
        migrations.CreateModel(
            name='EnderecosClientes',
            fields=[
                ('id_endereco_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cep_endereco_cliente', models.CharField(max_length=15)),
                ('logradouro_endereco_cliente', models.CharField(max_length=100)),
                ('numero_endereco_cliente', models.IntegerField()),
                ('bairro_endereco_cliente', models.CharField(max_length=45)),
                ('cidade_endereco_cliente', models.CharField(max_length=45)),
                ('estado_endereco_cliente', models.CharField(max_length=10)),
                ('fk_id_cliente', models.ForeignKey(db_column='fk_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='app_01.clientes')),
            ],
            options={
                'db_table': 'enderecos_clientes',
            },
        ),
        migrations.CreateModel(
            name='Fotografias',
            fields=[
                ('id_fotografia', models.AutoField(primary_key=True, serialize=False)),
                ('fotografia', models.ImageField(upload_to='images/fotografias/')),
                ('nome_arquivo_fotografia', models.CharField(max_length=100)),
                ('formato_fotografia', models.CharField(max_length=10)),
                ('tamanho_fotografia', models.CharField(max_length=10)),
                ('data_upload_fotografia', models.DateField(auto_now_add=True)),
                ('hora_upload_fotografia', models.TimeField(auto_now_add=True)),
                ('comentario_fotografia', models.CharField(blank=True, max_length=150, null=True)),
                ('fk_id_categoria', models.ForeignKey(db_column='fk_id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='app_01.categorias')),
                ('fk_id_fotografo', models.ForeignKey(db_column='fk_id_fotografo', on_delete=django.db.models.deletion.DO_NOTHING, to='app_01.fotografos')),
            ],
            options={
                'db_table': 'fotografias',
            },
        ),
        migrations.CreateModel(
            name='EnderecosFotografos',
            fields=[
                ('id_endereco_fotografo', models.AutoField(primary_key=True, serialize=False)),
                ('cep_endereco_fotografo', models.CharField(max_length=15)),
                ('logradouro_endereco_fotografo', models.CharField(max_length=100)),
                ('numero_endereco_fotografo', models.IntegerField()),
                ('bairro_endereco_fotografo', models.CharField(max_length=45)),
                ('cidade_endereco_fotografo', models.CharField(max_length=45)),
                ('estado_endereco_fotografo', models.CharField(max_length=10)),
                ('fk_id_fotografo', models.ForeignKey(db_column='fk_id_fotografo', on_delete=django.db.models.deletion.DO_NOTHING, to='app_01.fotografos')),
            ],
            options={
                'db_table': 'enderecos_fotografos',
            },
        ),
        migrations.AddField(
            model_name='fotografos',
            name='fk_id_fotografo_pf',
            field=models.ForeignKey(blank=True, db_column='fk_id_fotografo_pf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_01.fotografospf'),
        ),
        migrations.AddField(
            model_name='fotografos',
            name='fk_id_fotografo_pj',
            field=models.ForeignKey(blank=True, db_column='fk_id_fotografo_pj', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_01.fotografospj'),
        ),
        migrations.CreateModel(
            name='FotografosServicos',
            fields=[
                ('fk_id_fotografo', models.OneToOneField(db_column='fk_id_fotografo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_01.fotografos')),
                ('fk_id_servico', models.ForeignKey(db_column='fk_id_servico', on_delete=django.db.models.deletion.DO_NOTHING, to='app_01.servicos')),
            ],
            options={
                'db_table': 'fotografos_servicos',
                'unique_together': {('fk_id_fotografo', 'fk_id_servico')},
            },
        ),
        migrations.CreateModel(
            name='ServicosClientes',
            fields=[
                ('fk_id_servico', models.OneToOneField(db_column='fk_id_servico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_01.servicos')),
                ('fk_id_cliente', models.ForeignKey(db_column='fk_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='app_01.clientes')),
            ],
            options={
                'db_table': 'servicos_clientes',
                'unique_together': {('fk_id_servico', 'fk_id_cliente')},
            },
        ),
        migrations.CreateModel(
            name='ServicosTiposDeServicos',
            fields=[
                ('fk_id_servico', models.OneToOneField(db_column='fk_id_servico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_01.servicos')),
                ('fk_id_tipo_de_servico', models.ForeignKey(db_column='fk_id_tipo_de_servico', on_delete=django.db.models.deletion.DO_NOTHING, to='app_01.tiposdeservicos')),
            ],
            options={
                'db_table': 'servicos_tipos_de_servicos',
                'unique_together': {('fk_id_servico', 'fk_id_tipo_de_servico')},
            },
        ),
    ]
