# Generated by Django 5.1.2 on 2024-10-14 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adms',
            fields=[
                ('id_adm', models.AutoField(primary_key=True, serialize=False)),
                ('login_adm', models.CharField(max_length=45)),
                ('senha_adm', models.CharField(max_length=10)),
                ('nome_adm', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'adms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=70)),
                ('cpf_cliente', models.CharField(max_length=14)),
                ('email_cliente', models.CharField(max_length=45)),
                ('login_cliente', models.CharField(max_length=45)),
                ('senha_cliente', models.CharField(max_length=45)),
                ('endereco_cliente', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComentariosClientes',
            fields=[
                ('id_comentario_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('decricao_comentario_cliente', models.CharField(max_length=300)),
                ('data_comentario_cliente', models.DateField()),
                ('hora_comentario_cliente', models.TimeField()),
            ],
            options={
                'db_table': 'comentarios_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fotografias',
            fields=[
                ('id_fotografia', models.AutoField(primary_key=True, serialize=False)),
                ('link_fotografia', models.CharField(max_length=150)),
                ('formato_fotografia', models.CharField(max_length=100)),
                ('descricao_fotografia', models.CharField(max_length=100)),
                ('data_upload_fotografia', models.DateField()),
                ('hora_upload_fotografia', models.TimeField()),
                ('comentario_fotografia', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'fotografias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fotografos',
            fields=[
                ('id_fotografo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fotografo', models.CharField(max_length=70)),
                ('telefone_fotografo', models.CharField(max_length=45)),
                ('raio_atendimento_fotografo', models.CharField(max_length=70)),
                ('endereco_fotografo', models.CharField(max_length=200)),
                ('email_fotografo', models.CharField(max_length=45)),
                ('login_fotografo', models.CharField(max_length=45)),
                ('senha_fotografo', models.CharField(max_length=45)),
                ('descricao_fotografo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'fotografos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotografosPf',
            fields=[
                ('id_fotografo_pf', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_fotografo_pf', models.CharField(max_length=14)),
                ('apelido_profissional_fotografo_pf', models.CharField(max_length=45)),
                ('data_nascimento_fotografo_pf', models.DateField()),
                ('genero_fotografo_pf', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'fotografos_pf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotografosPj',
            fields=[
                ('id_fotografo_pj', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj_fotografo_pj', models.CharField(max_length=45)),
                ('razao_social_fotografo_pj', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fotografos_pj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('data_contratacao_servico', models.DateField()),
                ('hora_contratacao_servico', models.TimeField()),
                ('quantidade_servico', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'servicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposDeServicos',
            fields=[
                ('id_tipo_de_servico', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_tipo_de_servico', models.CharField(max_length=100)),
                ('valor_tipo_de_servico', models.FloatField()),
            ],
            options={
                'db_table': 'tipos_de_servicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotografosServicos',
            fields=[
                ('fk_id_fotografo', models.OneToOneField(db_column='fk_id_fotografo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_01.fotografos')),
            ],
            options={
                'db_table': 'fotografos_servicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicosClientes',
            fields=[
                ('fk_id_servico', models.OneToOneField(db_column='fk_id_servico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_01.servicos')),
            ],
            options={
                'db_table': 'servicos_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicosTiposDeServicos',
            fields=[
                ('fk_id_servico', models.OneToOneField(db_column='fk_id_servico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_01.servicos')),
            ],
            options={
                'db_table': 'servicos_tipos_de_servicos',
                'managed': False,
            },
        ),
    ]
