# Generated by Django 5.1.2 on 2024-10-15 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adms',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='ComentariosClientes',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Fotografias',
        ),
        migrations.RemoveField(
            model_name='fotografosservicos',
            name='fk_id_fotografo',
        ),
        migrations.DeleteModel(
            name='FotografosPf',
        ),
        migrations.DeleteModel(
            name='FotografosPj',
        ),
        migrations.RemoveField(
            model_name='servicosclientes',
            name='fk_id_servico',
        ),
        migrations.RemoveField(
            model_name='servicostiposdeservicos',
            name='fk_id_servico',
        ),
        migrations.DeleteModel(
            name='TiposDeServicos',
        ),
        migrations.DeleteModel(
            name='Fotografos',
        ),
        migrations.DeleteModel(
            name='FotografosServicos',
        ),
        migrations.DeleteModel(
            name='ServicosClientes',
        ),
        migrations.DeleteModel(
            name='Servicos',
        ),
        migrations.DeleteModel(
            name='ServicosTiposDeServicos',
        ),
    ]
