# Generated by Django 5.1.2 on 2024-10-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adms',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='ComentariosClientes',
        ),
        migrations.DeleteModel(
            name='Fotografias',
        ),
        migrations.RemoveField(
            model_name='fotografosservicos',
            name='fk_id_fotografo',
        ),
        migrations.DeleteModel(
            name='FotografosPf',
        ),
        migrations.DeleteModel(
            name='FotografosPj',
        ),
        migrations.RemoveField(
            model_name='servicosclientes',
            name='fk_id_servico',
        ),
        migrations.RemoveField(
            model_name='servicostiposdeservicos',
            name='fk_id_servico',
        ),
        migrations.DeleteModel(
            name='TiposDeServicos',
        ),
        migrations.DeleteModel(
            name='Fotografos',
        ),
        migrations.DeleteModel(
            name='FotografosServicos',
        ),
        migrations.DeleteModel(
            name='ServicosClientes',
        ),
        migrations.DeleteModel(
            name='Servicos',
        ),
        migrations.DeleteModel(
            name='ServicosTiposDeServicos',
        ),
    ]
