# Generated by Django 5.1.2 on 2024-10-25 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_01', '0004_delete_adms_delete_categorias_delete_clientes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adms',
            fields=[
                ('id_adm', models.AutoField(primary_key=True, serialize=False)),
                ('login_adm', models.CharField(max_length=45)),
                ('senha_adm', models.CharField(max_length=10)),
                ('nome_adm', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'adms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=70)),
                ('cpf_cliente', models.CharField(max_length=14)),
                ('email_cliente', models.CharField(max_length=45)),
                ('login_cliente', models.CharField(max_length=45)),
                ('senha_cliente', models.CharField(max_length=45)),
                ('endereco_cliente', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComentariosClientes',
            fields=[
                ('id_comentario_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('decricao_comentario_cliente', models.CharField(max_length=300)),
                ('data_comentario_cliente', models.DateField()),
                ('hora_comentario_cliente', models.TimeField()),
            ],
            options={
                'db_table': 'comentarios_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fotografias',
            fields=[
                ('id_fotografia', models.AutoField(primary_key=True, serialize=False)),
                ('link_fotografia', models.CharField(max_length=150)),
                ('formato_fotografia', models.CharField(max_length=100)),
                ('descricao_fotografia', models.CharField(max_length=100)),
                ('data_upload_fotografia', models.DateField()),
                ('hora_upload_fotografia', models.TimeField()),
                ('comentario_fotografia', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'fotografias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fotografos',
            fields=[
                ('id_fotografo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fotografo', models.CharField(max_length=70)),
                ('telefone_fotografo', models.CharField(max_length=45)),
                ('raio_atendimento_fotografo', models.CharField(max_length=70)),
                ('endereco_fotografo', models.CharField(max_length=200)),
                ('email_fotografo', models.CharField(max_length=45)),
                ('login_fotografo', models.CharField(max_length=45)),
                ('senha_fotografo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'fotografos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotografosPf',
            fields=[
                ('id_fotografo_pf', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_fotografo_pf', models.CharField(max_length=14)),
                ('apelido_profissional_fotografo_pf', models.CharField(max_length=45)),
                ('data_nascimento_fotografo_pf', models.DateField()),
                ('genero_fotografo_pf', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'fotografos_pf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotografosPj',
            fields=[
                ('id_fotografo_pj', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj_fotografo_pj', models.CharField(max_length=45)),
                ('razao_social_fotografo_pj', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fotografos_pj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('data_contratacao_servico', models.DateField()),
                ('hora_contratacao_servico', models.TimeField()),
                ('quantidade_servico', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'servicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposDeServicos',
            fields=[
                ('id_tipo_de_servico', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_tipo_de_servico', models.CharField(max_length=100)),
                ('valor_tipo_de_servico', models.FloatField()),
            ],
            options={
                'db_table': 'tipos_de_servicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotografosServicos',
            fields=[
                ('fk_id_fotografo', models.OneToOneField(db_column='fk_id_fotografo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_01.fotografos')),
            ],
            options={
                'db_table': 'fotografos_servicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicosClientes',
            fields=[
                ('fk_id_servico', models.OneToOneField(db_column='fk_id_servico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_01.servicos')),
            ],
            options={
                'db_table': 'servicos_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicosTiposDeServicos',
            fields=[
                ('fk_id_servico', models.OneToOneField(db_column='fk_id_servico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_01.servicos')),
            ],
            options={
                'db_table': 'servicos_tipos_de_servicos',
                'managed': False,
            },
        ),
    ]
