# Generated by Django 5.1.2 on 2024-10-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0006_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecosClientes',
            fields=[
                ('id_endereco_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cep_endereco_cliente', models.CharField(max_length=15)),
                ('logradouro_endereco_cliente', models.CharField(max_length=100)),
                ('numero_endereco_cliente', models.IntegerField()),
                ('bairro_endereco_cliente', models.CharField(max_length=45)),
                ('cidade_endereco_cliente', models.CharField(max_length=45)),
                ('estado_endereco_cliente', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'enderecos_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnderecosFotografos',
            fields=[
                ('id_endereco_fotografo', models.AutoField(primary_key=True, serialize=False)),
                ('cep_endereco_fotografo', models.CharField(max_length=15)),
                ('logradouro_endereco_fotografo', models.CharField(max_length=100)),
                ('numero_endereco_fotografo', models.IntegerField()),
                ('bairro_endereco_fotografo', models.CharField(max_length=45)),
                ('cidade_endereco_fotografo', models.CharField(max_length=45)),
                ('estado_endereco_fotografo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'enderecos_fotografos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Enderecos',
        ),
    ]
