# Generated by Django 5.1.2 on 2024-11-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0007_enderecosclientes_enderecosfotografos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adms',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='ComentariosClientes',
        ),
        migrations.DeleteModel(
            name='EnderecosClientes',
        ),
        migrations.DeleteModel(
            name='EnderecosFotografos',
        ),
        migrations.DeleteModel(
            name='Especialidades',
        ),
        migrations.DeleteModel(
            name='Fotografias',
        ),
        migrations.RemoveField(
            model_name='fotografosespecialidades',
            name='fk_id_fotografo',
        ),
        migrations.RemoveField(
            model_name='fotografosservicos',
            name='fk_id_fotografo',
        ),
        migrations.DeleteModel(
            name='FotografosPf',
        ),
        migrations.DeleteModel(
            name='FotografosPj',
        ),
        migrations.RemoveField(
            model_name='servicostiposdeservicos',
            name='fk_id_servico',
        ),
        migrations.RemoveField(
            model_name='servicosclientes',
            name='fk_id_servico',
        ),
        migrations.DeleteModel(
            name='TiposDeServicos',
        ),
        migrations.DeleteModel(
            name='FotografosEspecialidades',
        ),
        migrations.DeleteModel(
            name='Fotografos',
        ),
        migrations.DeleteModel(
            name='FotografosServicos',
        ),
        migrations.DeleteModel(
            name='ServicosTiposDeServicos',
        ),
        migrations.DeleteModel(
            name='Servicos',
        ),
        migrations.DeleteModel(
            name='ServicosClientes',
        ),
    ]
