# Generated by Django 5.1.2 on 2025-03-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Especialidades',
        ),
        migrations.DeleteModel(
            name='FotografosEspecialidades',
        ),
    ]
