# Generated by Django 5.1.2 on 2025-06-16 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0010_delete_especialidades_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentariosClientes',
        ),
    ]
