# Generated by Django 5.2.4 on 2025-07-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0011_delete_comentariosclientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='adms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enderecosclientes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enderecosfotografos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fotografias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fotografos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fotografospf',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fotografospj',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fotografosservicos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicosclientes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicostiposdeservicos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tiposdeservicos',
            options={},
        ),
    ]
