# Generated by Django 5.2.4 on 2025-07-21 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0012_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adms',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='EnderecosClientes',
        ),
        migrations.DeleteModel(
            name='EnderecosFotografos',
        ),
        migrations.DeleteModel(
            name='Fotografias',
        ),
        migrations.RemoveField(
            model_name='fotografosservicos',
            name='fk_id_fotografo',
        ),
        migrations.DeleteModel(
            name='FotografosPf',
        ),
        migrations.DeleteModel(
            name='FotografosPj',
        ),
        migrations.RemoveField(
            model_name='servicosclientes',
            name='fk_id_servico',
        ),
        migrations.RemoveField(
            model_name='servicostiposdeservicos',
            name='fk_id_servico',
        ),
        migrations.DeleteModel(
            name='TiposDeServicos',
        ),
        migrations.DeleteModel(
            name='Fotografos',
        ),
        migrations.DeleteModel(
            name='FotografosServicos',
        ),
        migrations.DeleteModel(
            name='ServicosClientes',
        ),
        migrations.DeleteModel(
            name='Servicos',
        ),
        migrations.DeleteModel(
            name='ServicosTiposDeServicos',
        ),
    ]
