# Generated by Django 5.1.2 on 2025-02-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_02', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adms',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='ComentariosClientes',
        ),
        migrations.DeleteModel(
            name='EnderecosClientes',
        ),
        migrations.DeleteModel(
            name='Especialidades',
        ),
        migrations.RemoveField(
            model_name='servicosclientes',
            name='fk_id_servico',
        ),
        migrations.DeleteModel(
            name='FotografosEspecialidades',
        ),
        migrations.DeleteModel(
            name='ServicosClientes',
        ),
    ]
