# Generated by Django 5.1.2 on 2025-03-15 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_02', '0002_delete_adms_delete_clientes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='EnderecosFotografos',
        ),
        migrations.DeleteModel(
            name='Fotografias',
        ),
        migrations.RemoveField(
            model_name='fotografosservicos',
            name='fk_id_fotografo',
        ),
        migrations.DeleteModel(
            name='FotografosPf',
        ),
        migrations.DeleteModel(
            name='FotografosPj',
        ),
        migrations.RemoveField(
            model_name='servicostiposdeservicos',
            name='fk_id_servico',
        ),
        migrations.DeleteModel(
            name='TiposDeServicos',
        ),
        migrations.DeleteModel(
            name='Fotografos',
        ),
        migrations.DeleteModel(
            name='FotografosServicos',
        ),
        migrations.DeleteModel(
            name='Servicos',
        ),
        migrations.DeleteModel(
            name='ServicosTiposDeServicos',
        ),
    ]
