# Generated by Django 5.1.2 on 2025-06-16 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_02', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adms',
            fields=[
                ('id_adm', models.AutoField(primary_key=True, serialize=False)),
                ('nome_adm', models.CharField(max_length=45)),
                ('email_adm', models.CharField(max_length=45)),
                ('senha_adm', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'adms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=70)),
                ('genero_cliente', models.CharField(max_length=15)),
                ('cpf_cliente', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone_cliente', models.CharField(max_length=45)),
                ('email_cliente', models.CharField(max_length=45)),
                ('senha_cliente', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnderecosClientes',
            fields=[
                ('id_endereco_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cep_endereco_cliente', models.CharField(max_length=15)),
                ('logradouro_endereco_cliente', models.CharField(max_length=100)),
                ('numero_endereco_cliente', models.IntegerField()),
                ('bairro_endereco_cliente', models.CharField(max_length=45)),
                ('cidade_endereco_cliente', models.CharField(max_length=45)),
                ('estado_endereco_cliente', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'enderecos_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicosClientes',
            fields=[
                ('fk_id_servico', models.OneToOneField(db_column='fk_id_servico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_02.servicos')),
            ],
            options={
                'db_table': 'servicos_clientes',
                'managed': False,
            },
        ),
    ]
