from django.urls import path
from .import views

urlpatterns = [
    path('', views.Carrega_home_page, name='carrega_home_page'),
    path('login/profissional-PF/', views.Carrega_login_profPF, name='login_profPF_page'),
    path('login/profissional-PJ/', views.Carrega_login_profPJ, name='login_profPJ_page'),
    path('login/cliente/', views.Carrega_login_cliente, name='login_cliente_page'),
    path('cadastro/profissionalPF/', views.Cadastra_profPF, name='cadastra_profPF'),   
    path('cadastro/profissionalPJ/', views.Cadastra_profPJ, name='cadastra_profPJ'),
    path('cliente/cadastro/', views.Cadastra_cliente, name='cadastra_cliente_page'),
    path('galeria/', views.Carrega_galeria, name='galeria_page'),
    path('categoria/ambiente/', views.categoria_ambiente, name='categoria_ambiente'),
    path('categoria/formatura/', views.categoria_formatura, name='categoria_formatura'),
    path('categoria/moda/', views.categoria_moda, name='categoria_moda'),
    path('categoria/aniversario/', views.categoria_aniversario, name='categoria_aniversario'),
    path('categoria/batizado/', views.categoria_batizado, name='categoria_batizado'),
    path('categoria/casamento/', views.categoria_casamento, name='categoria_casamento'),
    path('categoria/publicidae/', views.categoria_publicidade, name='categoria_publicidade'),
    path('categoria/arquitetura/', views.categoria_arquitetura, name='categoria_arquitetura'),
    path('categoria/esporte/', views.categoria_esporte, name='categoria_esporte'),
    path('categoria/filmmaker/', views.categoria_filmmaker, name='categoria_filmmaker'),
    path('categoria/newborn/', views.categoria_newborn, name='categoria_newborn'),
    path('categoria/gestante/', views.categoria_gestante, name='categoria_gestante'),
    path('categoria/gastronomia/', views.categoria_gastronomia, name='categoria_gastronomia'),
    path('sub/show/', views.sub_show, name='subcategoria_show'),
    path('sub/palestra/', views.sub_palestra, name='subcategoria_palestra'),
    path('sub/festa/', views.sub_festa, name='subcategoria_festa'),
    path('sub/geral/', views.sub_geral, name='subcategoria_geral'),
    path('sub/externo/', views.sub_externo, name='subcategoria_externo'),
    path('sub/estudio/', views.sub_estudio, name='subcategoria_estudio'),
    path('sub/estudio/', views.sub_estudio, name='subcategoria_estudio'),
    path('perfil/', views.Carrega_perfil, name='carrega_perfil'),
]
